# web-core image is meant to be used only by our safe-infrastructure repository

name: Deploy to Dockerhub

on:
  push:
    branches:
      - hemi-main
      - dev
  release:
    types: [released]

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hemi-main' || github.ref == 'refs/heads/dev' || (github.event_name == 'release' && github.event.action == 'released')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy Main
        if: github.ref == 'refs/heads/hemi-main'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hemilabs/safe-wallet-web:staging
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy Develop
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: hemilabs/safe-wallet-web:dev
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy Tag
        if: (github.event_name == 'release' && github.event.action == 'released')
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            hemilabs/safe-wallet-web:${{ github.event.release.tag_name }}
            hemilabs/safe-wallet-web:latest
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
